#!/bin/bash -ex
# Copyright 2012 NEC Corporation.
# All Rights Reserved.
#

[ -z ${MYSQL_PASS} ] && echo "Error: no MYSQL_PASS!" && exit 1
[ -z ${NDB_PASS} ] && echo "Error: no NDB_PASS!" && exit 1


# package list
base_pkgs="python-greenlet python-mysqldb nova-common python-nova"
user_pkgs="euca2ools unzip"
control_pkgs="rabbitmq-server nova-api nova-scheduler"
# include packages for qemu
compute_pkgs="nova-compute libvirt-dev kvm-pxe qemu"
network_pkgs="nova-network"
storage_pkgs="glance"
pkgs="$base_pkgs $control_pkgs $user_pkgs \
      $compute_pkgs $network_pkgs $storage_pkgs"

# install packages
sudo apt-get install -y python-software-properties
sudo add-apt-repository ppa:openstack-release/2011.3
sudo apt-get update
sudo apt-get install -y $pkgs

# Database
cat <<MYSQL_PRESEED | sudo debconf-set-selections
mysql-server-5.1 mysql-server/root_password password $MYSQL_PASS
mysql-server-5.1 mysql-server/root_password_again password $MYSQL_PASS
mysql-server-5.1 mysql-server/start_on_boot boolean true
MYSQL_PRESEED
sudo apt-get install -y mysql-server
sudo sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mysql/my.cnf
sudo service mysql restart
sleep 1
mysql -uroot -p$MYSQL_PASS << END
CREATE DATABASE nova;
GRANT ALL PRIVILEGES ON *.* TO 'nova'@'%' WITH GRANT OPTION;
SET PASSWORD FOR 'nova'@'%' = PASSWORD('$NDB_PASS');
SELECT user,host,password FROM mysql.user;
FLUSH PRIVILEGES;
END

# disable dnsmasq daemon
if [ -e "/usr/bin/dnsmasq" ]
then
	sudo update-rc.d dnsmasq disable
	sudo /etc/init.d/dnsmasq stop
	#sudo killall dnsmasq
fi

# network config
sudo su - -c "echo 1 > /proc/sys/net/ipv4/ip_forward"

# commentout nova-compute.conf
sudo sed -i -e "/^[^#]/s/^/#/" /etc/nova/nova-compute.conf
