#!/bin/bash -ex
# Copyright 2012 NEC Corporation.
# All Rights Reserved.
#

[ -z ${INSTALLER_DIR} ] && echo "Error: no INSTALLER_DIR!" && exit 1
[ -z ${TREMA_DIR} ] && echo "Error: no TREMA_DIR!" && exit 1


# install git 
[ -f /usr/bin/git ] || apt-get -y install git-core

# get code
pkgs="gcc make ruby ruby-dev irb file libjson-perl libpcap-dev sqlite3 \
libsqlite3-dev apache2-mpm-prefork libdbi-perl libdbd-sqlite3-perl \
libglib2.0-0"
sudo apt-get -y install $pkgs
git clone http://github.com/trema/trema.git $TREMA_DIR/trema
git clone http://github.com/trema/apps.git $TREMA_DIR/apps

# build
pushd $TREMA_DIR/trema
	./build.rb
popd
make -C $TREMA_DIR/apps/topology
make -C $TREMA_DIR/apps/sliceable_routing_switch

# prepare dir
SRS_DIR="$TREMA_DIR/apps/sliceable_routing_switch"
VAR_DIR="$SRS_DIR/var"
for dir in apache db log script
do
	mkdir -p $VAR_DIR/$dir
done

# config HTTP Server for sliceable_routing_switch
base="$INSTALLER_DIR/sliceable_routing_switch.base"
sed -e "s|@VAR@|$VAR_DIR|" $base > $VAR_DIR/apache/sliceable_routing_switch
sudo ln -s $VAR_DIR/apache/sliceable_routing_switch /etc/apache2/sites-available
sudo a2enmod rewrite actions
sudo a2ensite sliceable_routing_switch

# deploy files
pushd $SRS_DIR
	rm -f filter.db  slice.db
	./create_tables.sh
	mv filter.db  slice.db $VAR_DIR/db/
	cp Slice.pm Filter.pm config.cgi $VAR_DIR/script/
popd
sed -i -e "s|/home/sliceable_routing_switch/db|$VAR_DIR/db|" \
	$VAR_DIR/script/config.cgi
cp $SRS_DIR/sliceable_routing_switch_null.conf $VAR_DIR/srs.conf
sed -i -e "s|slice.db|var/db/slice.db|" -e "s|filter.db|var/db/filter.db|" \
	$VAR_DIR/srs.conf
sudo chown -R www-data.www-data $VAR_DIR

# reload apache
sudo /etc/init.d/apache2 reload

# start trema
pushd $TREMA_DIR/trema
	sudo ./trema run -d -c $VAR_DIR/srs.conf
popd
