#!/bin/bash -ex
# Copyright 2012 NEC Corporation.
# All Rights Reserved.
#

[ -z ${INSTALLER_DIR} ] && echo "Error: no INSTALLER_DIR!" && exit 1
[ -z ${IMAGE_TAR} -a -z ${IMAGE_URL} ] && echo "Error: no IMAGE!" && exit 1
nova_manage="sudo nova-manage --flagfile=/etc/nova/nova.conf"
tmp_dir="${INSTALLER_DIR}/tmp-images"
image=

include_image_info?() {
	dir=$1
	[ 1 = $(ls $dir/ami-*/info.json | wc -l) -a \
	  1 = $(ls $dir/aki-*/info.json | wc -l) ]
}

ubuntu_cloudimg?() {
	pre="$1"
	[ -f "$pre.img" -a  -f "$pre-vmlinuz-virtual" ]
}

guess_arch() {
	echo $1 | grep -q amd64 && echo "x86_64" || echo "i386"
}



[ -f "$IMAGE_TAR" ] && image="`pwd`/$IMAGE_TAR"
[ -f "${INSTALLER_DIR}/$IMAGE_TAR" ] && image="${INSTALLER_DIR}/$IMAGE_TAR"

# download image
if [ -z "$image" ]
then
	pushd "${INSTALLER_DIR}"
		wget "$IMAGE_URL"
		IMAGE_TAR="${IMAGE_URL##*/}"
		image="${INSTALLER_DIR}/$IMAGE_TAR"
	popd
fi
prefix=$(echo "$IMAGE_TAR" | sed -e "s/.tar.gz$//" -e "s/.tgz$//")

# extract image
mkdir -p "$tmp_dir"
tar xf "$IMAGE_TAR" -C "$tmp_dir"

# register VM image
if include_image_info? "$tmp_dir"
then
	$nova_manage image convert "$tmp_dir"
elif ubuntu_cloudimg? "$tmp_dir/$prefix"
then
	$nova_manage image all_register \
		--image=$prefix.img \
		--kernel=$prefix-vmlinuz-virtual \
		--ram=$prefix-initrd-virtual \
		--name=$prefix \
		--public=T \
		--arch=$(guess_arch $prefix)
else
	echo "[WARN] $0: Unkown IMAGE format, skip register image."
fi

rm -rf "$tmp_dir"
