#!/bin/bash -ex
# Copyright 2012 NEC Corporation.
# All Rights Reserved.
#

[ -z ${USER} ] && echo "Error: no USER!" && exit 1
[ -z ${PROJECT} ] && echo "Error: no PROJECT!" && exit 1
[ -z ${CREDS_DIR} ] && echo "Error: no CREDS_DIR!" && exit 1
nova_manage="sudo nova-manage --flagfile=/etc/nova/nova.conf"


mkdir -p ${CREDS_DIR}

# create user & project
$nova_manage db sync
$nova_manage user admin $USER > ${CREDS_DIR}/$USER.env
$nova_manage project create $PROJECT $USER

# create creds
$nova_manage project zipfile $PROJECT $USER ${CREDS_DIR}/novacreds.zip
unzip ${CREDS_DIR}/novacreds.zip -d ${CREDS_DIR}

# set nova env
#cat << END >> ~/.bashrc
#
#if [ -f ${CREDS_DIR}/novarc ] ;then . ${CREDS_DIR}/novarc; unset http_proxy; fi
#END
. ${CREDS_DIR}/novarc
unset http_proxy

# create keys
euca-add-keypair $USER > ${CREDS_DIR}/$USER.pem
chmod 600 ${CREDS_DIR}/$USER.pem

# set default network rule
euca-authorize -P icmp -t -1:-1 default
euca-authorize -P tcp -p 22 default
